// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJieMrt6Mn92yClKmnscHvhciwI3ZXJ3g',
    appId: '1:546927786059:web:fd89881773ef6d1498b5ce',
    messagingSenderId: '546927786059',
    projectId: 'reddit-2531f',
    authDomain: 'reddit-2531f.firebaseapp.com',
    storageBucket: 'reddit-2531f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA29uZwt8MpN8I6vIghmvUPMg8QOBvpZCI',
    appId: '1:546927786059:android:649b7c603aa258f998b5ce',
    messagingSenderId: '546927786059',
    projectId: 'reddit-2531f',
    storageBucket: 'reddit-2531f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKM3u8ORl9-z0T-VmazAwweoVZNrb77w0',
    appId: '1:546927786059:ios:4ad49bece78b0ed798b5ce',
    messagingSenderId: '546927786059',
    projectId: 'reddit-2531f',
    storageBucket: 'reddit-2531f.appspot.com',
    iosClientId: '546927786059-7nmkdhdqnjm10ooh44gb8dfa68pnafva.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
